;(package-install 'smex)
(package-install 'helm)
(package-install 'helm-gtags)
(package-install 'elpy)
(package-install 'auto-complete)
(package-install 'magit)
(package-install 'recentf)
(package-install 'ensime)
(package-install 'ido)
(package-install 'yasnippet)
(package-install 'markdown-mode)
(package-install 'autopair)
(package-install 'flymake-python-pyflakes)
;(package-install 'color-theme-molokai)


;;(require 'magit-autoloads)
;; (global-set-key (kbd "M-x") 'smex)
;; (global-set-key (kbd "M-X") 'smex-major-mode-commands)
(provide 'init-plugin)
